### ISSUE TITLE
Failure compiling

### ISSUE THREAD

**Issue by frios** [mfcollins3/SwiftMonacoEditor#6]
Hello,

Trying to use this package in a test app and keep failing to compile. If I add the package through Xcode's Package manager interface, I get an error

"Couldn't check out revision " with the revision # ending in eabf3

If I clone the repo locally and add it as a local package, when I try to compile I get the error:

"No such module 'MonocoEditor" on my import MonacoEditor line.

Any ideas how I can get past either of these errors?

**Comment by frios** [comment]
Resolved

**Comment by tp** [comment]
@frios What fixed it for you?

**Comment by frios** [comment]
Sorry, I moved on to another library and I cant remember what resolved the issue for me.
